### ISSUE TITLE
t/simple.t throws an exception

### ISSUE THREAD

**Issue by eseyman** [acme/test-www-mechanize-psgi#7]
When running prove -Ilib t/simple.t on 0.39's test suite, I get the following error:

> [...]
> ok 8 - Title is "Hi"
> ok 9 - Content contains "Hello World"
> ok 10 - An object of class 'Test::WWW::Mechanize::PSGI' isa 'Test::WWW::Mechanize::PSGI'
> \# PSGI error: Throwing an exception from app handler. Server shouldn't crash. at t/simple.t line 42.
> ok 11
> \# Subtest: env
>     ok 1 - Content contains "Joe"
>     1..1
> ok 12 - env
> 1..12
> ok

It appears the call to HTTP::Response->from_psgi() in simple_request() isn't working and this results in the exception being caught.

**Comment by oalders** [comment]
Thanks for reporting! Which version of Perl is this? Which platform? Which version of `HTTP::Response`?

**Comment by eseyman** [comment]
This is perl 5.28.2 running on Fedora 30. I'm using HTTP::Response 6.18.

Note that the maintainer of perl-Test-WWW-Mechanize-PSGI first saw the issue in Dec of 2017 so I don't think this is a recent thing.
https://bugzilla.redhat.com/show_bug.cgi?id=1520948#c1

**Comment by oalders** [comment]
Thanks for this.  Interestingly, the build matrix is totally green http://matrix.cpantesters.org/?dist=Test-WWW-Mechanize-PSGI+0.38 and http://matrix.cpantesters.org/?dist=Test-WWW-Mechanize-PSGI+0.39

**Comment by oalders** [comment]
Actually, this isn't a bug.  That's just a diagnostic message from the test.  The test passes.  The test is ensuring that an exception thrown inside the PSGI app doesn't cause the app to crash.  The app lives, so the test passes.  It's just the exception getting printed to the test output that is making this confusing.

**Comment by oalders** [comment]
Also note that this is where the diagnostic message is coming from: https://github.com/acme/test-www-mechanize-psgi/blob/master/lib/Test/WWW/Mechanize/PSGI.pm#L49
